version: '3.4'

services:
   web:
    container_name: boban-bot-2
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - './:/home/app/'
    environment:
      - FLASK_APP=./server/app.py
      - FLASK_DEBUG=1